### ISSUE TITLE
Unable to use oCam_viewer on Xubuntu 16.04

### ISSUE THREAD

**Issue by kevin-george** [withrobot/oCam#4]
I have been trying to use oCam with a system running on Xubuntu 16.04

The camera shows up as a USB device with dmesg
But when is run ls /dev/video*, the camera doesn't show up as a video device. 

The oCam viewer doesn't list it as well. 

Is there anything that can be done to debug this?

**Comment by kikislater** [comment]
Plug the board and type in a terminal : 
`dmesg`

What is the output in terminal of : 
`lsusb`

**Comment by nulesus** [comment]
Bus 011 Device 003: ID 1f75:0888 Innostor Technology Corporation IS888 SATA Storage Controller
Bus 011 Device 002: ID 2109:0811 VIA Labs, Inc. Hub
Bus 011 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 010 Device 004: ID 0e8d:1887 MediaTek Inc. 
Bus 010 Device 002: ID 2109:0811 VIA Labs, Inc. Hub
Bus 010 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 004: ID 05a4:988b Ortek Technology, Inc. 
Bus 003 Device 003: ID 0472:0065 Chicony Electronics Co., Ltd PFU-65 Keyboard [Chicony]
Bus 003 Device 002: ID 0472:0065 Chicony Electronics Co., Ltd PFU-65 Keyboard [Chicony]
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 009 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 008 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 007 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 006 Device 003: ID 1c07:0001  
Bus 006 Device 002: ID 046d:c24a Logitech, Inc. G600 Gaming Mouse
Bus 006 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by nulesus** [comment]
[ 6080.919429] usb 11-2: new SuperSpeed USB device number 4 using xhci_hcd
[ 6080.930671] usb 11-2: LPM exit latency is zeroed, disabling LPM.
[ 6086.355326] usb 11-2: unable to read config index 0 descriptor/all
[ 6086.355341] usb 11-2: can't read configurations, error -110
[ 6086.734007] usb 11-2: new SuperSpeed USB device number 5 using xhci_hcd
[ 6086.744959] usb 11-2: LPM exit latency is zeroed, disabling LPM.
[ 6092.169971] usb 11-2: unable to read config index 0 descriptor/all
[ 6092.169986] usb 11-2: can't read configurations, error -110
[ 6092.548618] usb 11-2: new SuperSpeed USB device number 6 using xhci_hcd
[ 6092.559531] usb 11-2: LPM exit latency is zeroed, disabling LPM.
[ 6097.984598] usb 11-2: unable to read config index 0 descriptor/all
[ 6097.984612] usb 11-2: can't read configurations, error -110
[ 6098.363181] usb 11-2: new SuperSpeed USB device number 7 using xhci_hcd
[ 6098.374271] usb 11-2: LPM exit latency is zeroed, disabling LPM.
[ 6103.799103] usb 11-2: unable to read config index 0 descriptor/all
[ 6103.799109] usb 11-2: can't read configurations, error -110
[ 6103.820237] usb usb11-port2: unable to enumerate USB device
[ 6103.820867] xhci_hcd 0000:04:00.0: Stop endpoint command completion for disabled slot 5
[ 6661.397245] r8169 0000:03:00.0 enp3s0: link down
[ 6663.411236] r8169 0000:03:00.0 enp3s0: link up
[ 6665.179705] r8169 0000:03:00.0 enp3s0: link down
[ 6667.199434] r8169 0000:03:00.0 enp3s0: link up
[ 6668.964734] r8169 0000:03:00.0 enp3s0: link down
[ 6670.968769] r8169 0000:03:00.0 enp3s0: link up
[ 6680.139373] r8169 0000:03:00.0 enp3s0: link down
[ 6682.118438] r8169 0000:03:00.0 enp3s0: link up
[ 6682.849450] r8169 0000:03:00.0 enp3s0: link down
[ 6684.781604] r8169 0000:03:00.0 enp3s0: link up
[ 6688.579488] r8169 0000:03:00.0 enp3s0: link down
[ 6690.594432] r8169 0000:03:00.0 enp3s0: link up
[ 6691.538848] r8169 0000:03:00.0 enp3s0: link down
[ 6693.498767] r8169 0000:03:00.0 enp3s0: link up
[ 6695.336929] r8169 0000:03:00.0 enp3s0: link down
[ 6697.277545] r8169 0000:03:00.0 enp3s0: link up
[ 6698.500766] r8169 0000:03:00.0 enp3s0: link down
[ 6700.510064] r8169 0000:03:00.0 enp3s0: link up
[ 7542.759763] usb usb11-port2: config error
